// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package model

import (
	"context"
	"database/sql"
	"time"

	"cs-api/pkg/types"
)

type Querier interface {
	AcceptRoom(ctx context.Context, arg AcceptRoomParams) error
	CheckFastReplyCategory(ctx context.Context, id int64) (interface{}, error)
	CheckMerchantKey(ctx context.Context, key string) (int64, error)
	CloseRoom(ctx context.Context, arg CloseRoomParams) error
	ConstantSeeder(ctx context.Context) error
	// 計算每日分類諮詢數
	CountClosedRoomByTag(ctx context.Context, arg CountClosedRoomByTagParams) ([]CountClosedRoomByTagRow, error)
	// 計算每日訪客數
	CountDailyRoomByMember(ctx context.Context, arg CountDailyRoomByMemberParams) (int64, error)
	CountListFAQ(ctx context.Context) (int64, error)
	CountListFastReply(ctx context.Context) (int64, error)
	CountListMember(ctx context.Context) (int64, error)
	CountListMerchant(ctx context.Context) (int64, error)
	CountListMessage(ctx context.Context) (int64, error)
	CountListNotice(ctx context.Context) (int64, error)
	CountListRemind(ctx context.Context) (int64, error)
	CountListRole(ctx context.Context) (int64, error)
	CountListRoom(ctx context.Context) (int64, error)
	CountListStaff(ctx context.Context) (int64, error)
	CountListStaffRoom(ctx context.Context, status types.RoomStatus) (int64, error)
	CountListTag(ctx context.Context) (int64, error)
	CreateFAQ(ctx context.Context, arg CreateFAQParams) error
	CreateFastReply(ctx context.Context, arg CreateFastReplyParams) error
	CreateFastReplyCategory(ctx context.Context, arg CreateFastReplyCategoryParams) error
	CreateMember(ctx context.Context, arg CreateMemberParams) (sql.Result, error)
	CreateMerchant(ctx context.Context, arg CreateMerchantParams) error
	CreateMessage(ctx context.Context, arg CreateMessageParams) error
	CreateNotice(ctx context.Context, arg CreateNoticeParams) error
	CreateRemind(ctx context.Context, arg CreateRemindParams) error
	CreateReportDailyGuest(ctx context.Context, arg CreateReportDailyGuestParams) error
	CreateReportDailyTag(ctx context.Context, arg CreateReportDailyTagParams) error
	CreateRole(ctx context.Context, arg CreateRoleParams) error
	CreateRoom(ctx context.Context, arg CreateRoomParams) (sql.Result, error)
	CreateStaff(ctx context.Context, arg CreateStaffParams) error
	CreateTag(ctx context.Context, arg CreateTagParams) error
	DeleteFAQ(ctx context.Context, id int64) error
	DeleteFastReply(ctx context.Context, id int64) error
	DeleteMerchant(ctx context.Context, id int64) error
	DeleteNotice(ctx context.Context, id int64) error
	DeleteRemind(ctx context.Context, id int64) error
	DeleteReportDailyGuest(ctx context.Context, date time.Time) error
	DeleteReportDailyTag(ctx context.Context, date time.Time) error
	DeleteRole(ctx context.Context, id int64) error
	DeleteStaff(ctx context.Context, id int64) error
	DeleteTag(ctx context.Context, id int64) error
	GetAllAvailableFastReply(ctx context.Context) ([]GetAllAvailableFastReplyRow, error)
	GetAllRoles(ctx context.Context) ([]GetAllRolesRow, error)
	GetAllStaffs(ctx context.Context) ([]GetAllStaffsRow, error)
	GetAllTag(ctx context.Context) ([]Tag, error)
	GetCsConfig(ctx context.Context) (Constant, error)
	GetFAQ(ctx context.Context, id int64) (GetFAQRow, error)
	GetFastReply(ctx context.Context, id int64) (FastReply, error)
	GetGuestMember(ctx context.Context, deviceID string) (Member, error)
	GetLatestNotice(ctx context.Context) (GetLatestNoticeRow, error)
	// 獲取會員並未關閉的房間
	GetMemberAvailableRoom(ctx context.Context, memberID int64) (Room, error)
	GetMerchant(ctx context.Context, id int64) (GetMerchantRow, error)
	GetNormalMember(ctx context.Context, name string) (Member, error)
	GetNotice(ctx context.Context, id int64) (Notice, error)
	GetOnlineStatus(ctx context.Context, id int64) (types.MemberOnlineStatus, error)
	GetRemind(ctx context.Context, id int64) (Remind, error)
	GetRole(ctx context.Context, id int64) (Role, error)
	GetRoom(ctx context.Context, id int64) (GetRoomRow, error)
	GetStaff(ctx context.Context, id int64) (GetStaffRow, error)
	GetStaffCountByRoleId(ctx context.Context, roleID int64) (int64, error)
	GetStaffRoom(ctx context.Context, staffID int64) ([]int64, error)
	GetTag(ctx context.Context, id int64) (GetTagRow, error)
	ListActiveRemind(ctx context.Context) ([]ListActiveRemindRow, error)
	ListAvailableFAQ(ctx context.Context) ([]ListAvailableFAQRow, error)
	ListAvailableMerchant(ctx context.Context) ([]ListAvailableMerchantRow, error)
	ListAvailableStaff(ctx context.Context, id int64) ([]ListAvailableStaffRow, error)
	ListAvailableTag(ctx context.Context) ([]ListAvailableTagRow, error)
	ListFAQ(ctx context.Context, arg ListFAQParams) ([]ListFAQRow, error)
	ListFastReply(ctx context.Context, arg ListFastReplyParams) ([]ListFastReplyRow, error)
	ListFastReplyCategory(ctx context.Context) ([]Constant, error)
	ListMember(ctx context.Context, arg ListMemberParams) ([]Member, error)
	ListMemberRoomMessage(ctx context.Context, arg ListMemberRoomMessageParams) ([]Message, error)
	ListMerchant(ctx context.Context, arg ListMerchantParams) ([]ListMerchantRow, error)
	ListMessage(ctx context.Context, arg ListMessageParams) ([]Message, error)
	ListNotice(ctx context.Context, arg ListNoticeParams) ([]ListNoticeRow, error)
	ListRemind(ctx context.Context, arg ListRemindParams) ([]Remind, error)
	ListReportDailyGuest(ctx context.Context, arg ListReportDailyGuestParams) ([]ReportDailyGuest, error)
	ListReportDailyTag(ctx context.Context, arg ListReportDailyTagParams) ([]ReportDailyTag, error)
	ListRole(ctx context.Context, arg ListRoleParams) ([]Role, error)
	ListRoom(ctx context.Context, arg ListRoomParams) ([]ListRoomRow, error)
	ListStaff(ctx context.Context, arg ListStaffParams) ([]ListStaffRow, error)
	ListStaffRoom(ctx context.Context, arg ListStaffRoomParams) ([]ListStaffRoomRow, error)
	ListStaffRoomMessage(ctx context.Context, arg ListStaffRoomMessageParams) ([]Message, error)
	ListTag(ctx context.Context, arg ListTagParams) ([]ListTagRow, error)
	RoleSeeder(ctx context.Context) error
	StaffLogin(ctx context.Context, arg StaffLoginParams) (StaffLoginRow, error)
	StaffSeeder(ctx context.Context, password string) error
	TagSeeder(ctx context.Context) error
	UpdateCsConfig(ctx context.Context, arg UpdateCsConfigParams) error
	UpdateFAQ(ctx context.Context, arg UpdateFAQParams) error
	UpdateFastReply(ctx context.Context, arg UpdateFastReplyParams) error
	UpdateMerchant(ctx context.Context, arg UpdateMerchantParams) error
	UpdateNotice(ctx context.Context, arg UpdateNoticeParams) error
	UpdateOnlineStatus(ctx context.Context, arg UpdateOnlineStatusParams) error
	UpdateRemind(ctx context.Context, arg UpdateRemindParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	UpdateRoomScore(ctx context.Context, arg UpdateRoomScoreParams) error
	UpdateRoomStaff(ctx context.Context, arg UpdateRoomStaffParams) error
	UpdateStaff(ctx context.Context, arg UpdateStaffParams) error
	UpdateStaffAvatar(ctx context.Context, arg UpdateStaffAvatarParams) error
	UpdateStaffLogin(ctx context.Context, arg UpdateStaffLoginParams) error
	UpdateStaffServingStatus(ctx context.Context, arg UpdateStaffServingStatusParams) error
	UpdateStaffWithPassword(ctx context.Context, arg UpdateStaffWithPasswordParams) error
	UpdateTag(ctx context.Context, arg UpdateTagParams) error
}

var _ Querier = (*Queries)(nil)
