apiVersion: v1
kind: Service
metadata:
  name: cs-api
  namespace: cs-system
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: cs-api
  type: ClusterIP
